#create command to run pipeline using python3 src/main.py

MAIN_PATH = src/
MAIN_FILE = main.py
PYTHON = python3

.PHONY: run

# Create a command to run the pipeline
run:
	$(PYTHON) $(MAIN_PATH)$(MAIN_FILE)
	@echo "Pipeline run complete."